blogproject/blog/urls.py
from django.urls import path
from . import views

# app_name = 'blog'
# urlpatterns = [path(r'', views.index, name='index'),
#                path(r'post/<int:pk>/', views.detail, name='detail'),
#                path(r'post/<year>/<month>', views.archives,
#                     name='archives'),
#                path(r'category/<int:pk>', views.categories,
#                     name='categories'),
#                path(r'tag/<int:pk>', views.tags, name='tags'),
#                # path(r'search/', views.search, name='search'),  #这个是简单的搜索功能，搜索结果只是文章的列表，并不知道具体位置
#                 ]

app_name = 'blog'
urlpatterns = [path(r'', views.IndexView.as_view(), name='index'),
               path(r'post/<int:pk>/', views.DetailViews.as_view(), name='detail'),
               path(r'post/<year>/<month>', views.ArchivesView.as_view(), name='archives'),
               path(r'category/<int:pk>', views.CategoriesView.as_view(), name='categories'),
               path(r'tag/<int:pk>', views.TagsView.as_view(), name='tags'),
               # path(r'search/', views.search, name='search'),  #这个是简单的搜索功能，搜索结果只是文章的列表，并不知道具体位置
                ]

blogproject/blogproject/urls.py
from django.urls import path, include
from django.contrib import admin
from blog.feeds import AllRssPostsFeed
from users.views import index

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('blog.urls')),
    path(r'', include('comments.urls')),
    path(r'all/rss/', AllRssPostsFeed(), name='rss'),
    path(r'search/', include('haystack.urls')),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),


]

blogproject/users/urls.py
from django.urls import path
from users.views import register, index

app_name = 'users'
urlpatterns = [
    path(r'register/', register, name='register'),
    path(r'', index, name='index'),
    # path(r'', reset_password, name='reset_password')
]

blogproject/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>小云柳 &amp; blog</title>
    <style>
        span.highlighted {
            color: #32ebff;
        }
    </style>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">
    <!-- js -->
    <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                    <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">注销</a></li>
                    </ul>
                {% else %}
                    <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}?next={{ request.path }}">注册</a></button>
                    </p>
                {% endif %}
            </div><!--/.nav-collapse -->
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>小云柳</b> &amp; 东来东往</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="full-width.html" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="#" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc%}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                        暂无文章！
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as archives_list %}
                    <ul>
                        {% for date in archives_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年{{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as categories_list %}
                    <ul>
                        {% for category in categories_list %}
                        <li>
                            <a href="{% url 'blog:categories' category.pk %}">{{ category.name }}<span class="post-count">({{ category.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                       <h3 class="widget-title">标签云</h3>
                  {% get_tag as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tags' tag.pk %}">{{ tag.name }}<span class="post-count">({{ tag.num_posts }})</span></a>
                        </li>
                        {% empty %}
                        暂无标签！
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2018 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    -<a href="http://zmrenwu.com/" title="网页模板" target="_blank">借鉴于追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

blogproject/templates/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}">注册</a></button>
                </p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>